
POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "muzzamil",
  "secret": "pass1234"
}

###

POST http://localhost:3001/signup
Content-Type: application/json

{
  "username": "muzzamil",
  "secret": "pass1234",
  "email": "muzz@gmail.com",
  "first_name": "muzzamil",
  "last_name": "engine"
}
